### ISSUE TITLE
Idea: Joi should be in the peerDependencies section

### ISSUE THREAD

**Issue by mrjono1** [mrjono1/joi-to-typescript#27]
I'm pretty sure that Joi should be a peer dependency instead of a normal dependency.

I haven't had a use case like this before so I will investigate if this is the case I may do a major version bump for this change.

**Comment by mrjono1** [comment]
It will probably mean that this library should have more tests using multiple versions of joi

**Comment by hazmah0** [comment]
I was thinking about this briefly as well a few days ago when I was trying this package out. The project I was working on had a dependency to a package, lets call it A, and this package A was using version `14.x` of Joi internally.

When I added `joi-to-typescript` to convert the Joi schemas to TS types I saw the following output:
`[object Object] - Skipped - no Joi Schemas found`

And the reason for this is because I always ended up in this if statement below:
```
if (!Joi.isSchema(joiSchema)) {
  continue;
}
```

Since this package is using methods like `isSchema` and `describe` which only exists in newer versions of Joi I think it would make sense to add Joi as a peer dependency to express compatibility more clearly.

**Comment by mrjono1** [comment]
@hazmah0 that sounds like another issue, this library has only been tested with joi version 17 and greater. 
at version 17 Joi changed direction a bit (being split from hapi)
When I started this library I had lots of issues with versions of Joi less than 17 due to internal structure changes, it may work but I don't want to support old Joi versions.

**Comment by mrjono1** [comment]
sorry I didn't finish reading your comment you explained the issues I found with versions of joi less than 17

**Comment by mrjono1** [comment]
This has now been completed https://github.com/mrjono1/joi-to-typescript/releases/tag/3.0.0
